import type { KanbanState } from "./types";

/** Default columns with no tasks (for new boards). */
export function getEmptyBoardState(): KanbanState {
  return {
    columns: [
      { id: "backlog", titleKey: "backlog", taskIds: [] },
      { id: "in-progress", titleKey: "inProgress", taskIds: [] },
      { id: "done", titleKey: "done", taskIds: [] },
    ],
    tasks: {},
  };
}

export const INITIAL_KANBAN_STATE: KanbanState = {
  columns: [
    { id: "backlog", titleKey: "backlog", taskIds: ["t1", "t2", "t3", "t4"] },
    { id: "in-progress", titleKey: "inProgress", taskIds: ["t5", "t6", "t7"] },
    { id: "done", titleKey: "done", taskIds: ["t8", "t9"] },
  ],
  tasks: {
    t1: {
      id: "t1",
      title: "Integrate Stripe payment gateway",
      description:
        "Compile competitor landing page designs for inspiration. Gather assets and copy.",
      columnId: "backlog",
      priority: "high",
      progress: 33,
      assignees: ["m1", "m2"],
      checklist: [
        { id: "c1-1", title: "Research Stripe API docs", checked: true },
        { id: "c1-2", title: "Implement checkout session", checked: false },
        { id: "c1-3", title: "Add webhook handler", checked: false },
      ],
      createdAt: "2025-02-20T09:00:00.000Z",
      dueDate: "2025-03-15",
      attachments: [
        {
          id: "a1-1",
          name: "stripe-docs.pdf",
          url: "/files/stripe-docs.pdf",
          type: "file",
        },
        {
          id: "a1-2",
          name: "wireframe.png",
          url: "/files/wireframe.png",
          type: "image",
        },
      ],
      attachmentsCount: 2,
      commentsCount: 4,
    },
    t2: {
      id: "t2",
      title: "Redesign marketing homepage",
      description: "Update hero section and CTA placement for A/B testing.",
      columnId: "backlog",
      priority: "medium",
      progress: 0,
      assignees: ["m3"],
      checklist: [],
      createdAt: "2025-02-21T10:30:00.000Z",
      dueDate: null,
      attachments: [
        {
          id: "a2-1",
          name: "hero-mockup.jpg",
          url: "/files/hero-mockup.jpg",
          type: "image",
        },
      ],
      attachmentsCount: 1,
      commentsCount: 1,
    },
    t3: {
      id: "t3",
      title: "API rate limiting and caching",
      description: "Add Redis cache and rate limits for public API endpoints.",
      columnId: "backlog",
      priority: "medium",
      progress: 0,
      assignees: ["m4", "m5"],
      checklist: [],
      createdAt: "2025-02-22T14:00:00.000Z",
      dueDate: "2025-03-01",
      attachments: [],
      attachmentsCount: 0,
      commentsCount: 2,
    },
    t4: {
      id: "t4",
      title: "User notification preferences",
      description: "Settings page for email/push notification toggles.",
      columnId: "backlog",
      priority: "low",
      progress: 0,
      assignees: [],
      checklist: [],
      createdAt: "2025-02-23T08:00:00.000Z",
      dueDate: null,
      attachments: [],
      attachmentsCount: 0,
      commentsCount: 0,
    },
    t5: {
      id: "t5",
      title: "Dark mode toggle implementation",
      description: "Theme provider and CSS variables for dark/light modes.",
      columnId: "in-progress",
      priority: "high",
      progress: 50,
      assignees: ["m6", "m7"],
      checklist: [
        { id: "c5-1", title: "Add theme provider", checked: true },
        { id: "c5-2", title: "Define CSS variables", checked: true },
        { id: "c5-3", title: "Toggle component", checked: false },
        { id: "c5-4", title: "Persist preference", checked: false },
      ],
      createdAt: "2025-02-18T11:00:00.000Z",
      dueDate: "2025-02-28",
      attachments: [],
      attachmentsCount: 0,
      commentsCount: 6,
    },
    t6: {
      id: "t6",
      title: "Database schema refactoring",
      description: "Normalize tables and add indexes for reporting queries.",
      columnId: "in-progress",
      priority: "medium",
      progress: 55,
      assignees: ["m1", "m4"],
      checklist: [],
      createdAt: "2025-02-19T09:00:00.000Z",
      dueDate: "2025-03-10",
      attachments: [],
      attachmentsCount: 0,
      commentsCount: 2,
    },
    t7: {
      id: "t7",
      title: "Mobile responsive navigation",
      description: "Hamburger menu and drawer for small screens.",
      columnId: "in-progress",
      priority: "high",
      progress: 30,
      assignees: ["m8"],
      checklist: [],
      createdAt: "2025-02-24T16:00:00.000Z",
      dueDate: null,
      attachments: [],
      attachmentsCount: 0,
      commentsCount: 3,
    },
    t8: {
      id: "t8",
      title: "Set up CI/CD pipeline",
      description: "GitHub Actions for lint, test, and deploy to staging.",
      columnId: "done",
      priority: "high",
      progress: 100,
      assignees: ["m1", "m3"],
      checklist: [
        { id: "c8-1", title: "Lint job", checked: true },
        { id: "c8-2", title: "Test job", checked: true },
        { id: "c8-3", title: "Deploy to staging", checked: true },
      ],
      createdAt: "2025-02-10T08:00:00.000Z",
      dueDate: "2025-02-25",
      attachments: [],
      attachmentsCount: 0,
      commentsCount: 4,
    },
    t9: {
      id: "t9",
      title: "Initial project setup",
      description: "Next.js, ESLint, Tailwind, and repo structure.",
      columnId: "done",
      priority: "medium",
      progress: 100,
      assignees: ["m2", "m4"],
      checklist: [],
      createdAt: "2025-02-01T10:00:00.000Z",
      dueDate: "2025-02-20",
      attachments: [],
      attachmentsCount: 0,
      commentsCount: 2,
    },
  },
};
